version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  task-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo
