name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.2
        ports:
          - 27017:27017

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use node 18.11.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.11.0"
      - run: npm ci
      - run: npm run lint
      - run: npm run compile
      - run: npm test